services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data-volume:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  producer:
    build: ./producer
    restart: unless-stopped
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    restart: unless-stopped
    depends_on:
      - kafka
      - mongodb

  mailer:
    build: ./mailer
    restart: unless-stopped
    depends_on:
      - maildev

  maildev:
    image: maildev/maildev:latest
    restart: unless-stopped
    ports:
      - "1080:1080"  # Interface web accessible sur http://localhost:1080
      - "1025:1025"  # Serveur SMTP sur port 1025

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mongodb

volumes:
  mongodb-data-volume:
